function [critical_incidents, CI_weight] = get_critical_events()

critical_incidents = {'struck';...
                      'fatality';...
                      'suicide';...
                      'fatalities';...
                      'incident';...
                      'killed';...
                      'coroner';...
                      'police';...
                      'trespasser';...
                      'emergency';...
                      'hit';...
                      'collision';...
                      'car'};
CI_weight = [0.75;...
             1;...
             1;...
             1;...
             0.5;...
             0.75;...
             1;...
             0.0;...
             0.5;...
             0.25;...
             0.25;...
             0.5;...
             0.5];
                  
% critical_incidents = {'struck';...
%                       'incident';...
%                       'site';...
%                       'fatality';...
%                       'struck';...
%                       'suicide';...
%                       'fatalities'};

% critical_incidents      = {'fatal',        10;...
%                            'killed',       10;...
%                            'suicide',      10;...
%                            'incident',      8;...
%                            'accident',      8;...
%                            'struck',        7;...
%                            'indefinitely',  7;...
%                            'cancel',        4;...
%                            'severe',        4;...
%                            'broke',         4;...
%                            'mechanical',    4;...    
%                            'restrict',      2;...
%                            'signal',        2;...
%                            'single track',  3;...
%                            'all trains',    4};