function status_descriptors = get_minor_events();


%     status_descriptors.timing = {'min';'mn';'minutes';'hr';'hour'};
%     status_descriptors.location = {'arrive';'depart';'left';'at';'@';'to';'north of';'south of'; 'near'};
%     status_descriptors.status = {'delay';'late';'down'};

status_descriptors = {'down';...
                      'mins';...
                      'departed';...
                      'depart';...
                      'late';...
                      'min';...
                      'leaving';...
                      'left';...
                      'now';...
                      'minutes';...
                      'hour';...
                      'hr'
                      'mn'};
          