labels = {'Current Time';...
         'Frame Count';...
         'isRealtime';...
         'CIP';...
         'CIP counter';...
         'Tweet Time Stamp';...
         'Tweets Per Hour';...
         'Delta T';...
          'CI - struck';...
          'CI - fatality';...
          'CI - suicide';...
          'CI - fatalities';...
          'CI - incident';...
          'CI - killed';...
          'CI - coroner';...
          'CI - police';...
          'CI - trespasser';...
          'CI - emergency';...
          'CI - hit';...
          'CI - collision';...
          'CI - car';...
          'CI Count';...
          'Num Associated Trains';...
          'MI - down';...
          'MI - mins';...
          'MI - departed';...
          'MI - depart';...
          'MI - late';...
          'MI - min';...
          'MI - leaving';...
          'MI - left';...
          'MI - now';...
          'MI - minutes';...
          'MI - hour';...
          'MI - hr'
          'MI - mn'};
      
fid = fopen('CaltrainPerformanceData.dat','r');

Data = fread(fid,inf);
